routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('custom','AdminController@props')->name('props');
Route::get('/','PagesController@welcome')->name('welcome-home');

Route::namespace('Auth')->group(function (){
    Route::get('login','LoginController@showLoginForm')->name('login');
    Route::post('login','LoginController@postLogin')->name('post.login');
    Route::post('user/logout','LoginController@logout')->name('user.logout');

});

// Route::group(['middleware'=>'guest'], function(){
Route::get('com_service/verify/{token}', 'mailController@community_val_request')->name('community_validation');

//For accessing chapel service record for the student
Route::get('chapel_service/verify/{token}', 'mailController@chapel_val_request')->name('chapel_validation');
//For accessing physical fitness record for the student
Route::get('physical/xdfbbsbfjsdbfjf/{token}','mailController@physical_val_request')->name('physical_validation');

Route::get('warden/verify/{token}', 'mailController@warden_val_request')->name('warden_validation');
Route::get('remark/chaplain/{token}', 'mailController@remark_chap_val_request')->name('chaplain_remark_validation');
Route::post('community-warden-verify','CommunityServiceController@warden_update_verify')->name('community_warden_verify');
Route::post('chaplain-alpha-remark','CommunityServiceController@remark_chaplain')->name('remark_of_chaplain');
// });


Route::post('chapel-verify','CommunityServiceController@chapel_update_verify')->name('ess_chapel_verify');

//Physical fitness verification by the ESS if he wants to endorse the peculiar request
Route::post('physical-verify','CommunityServiceController@physical_update_verify')->name('ess_physical_verify');


Route::middleware(['auth:web'])->group(function(){

    Route::prefix('student')->group(function (){

    Route::get('pass_word',function(){
        return view('auth.passwords.change-pass');
    })->name('key');

    Route::post('pass','PagesController@password');
    Route::get('help','PagesController@help')->name('help');

    Route::resource('book','PagesController');

    Route::prefix('personal-details')->group(function (){

        Route::get('index', 'PagesController@show')->name('personal.show');
        Route::any('create','PagesController@create')->name('personal.create');
        Route::any('edit',  'PagesController@edit')->name('personal.edit');

    });

    Route::resource('diary','DiaryController');
    Route::resource('attach','AttachmentController');
    Route::resource('mentor','MentorController');
    Route::get('mentor/email/{token}','MentorController@getemail');
    Route::any('send-request-intern','AttachmentController@intern_notify')->name('intern-notification');
    Route::post('chapel_save','CommunityServiceController@ChapelSave')->name('chapel-post');
    Route::post('physical_save','CommunityServiceController@post_phyiscal_data')->name('physical-post');
    Route::post('attach/{id}','AttachmentController@update');
    Route::post('/book/get/{reg_num}','PagesController@update');
    Route::post('/diary/{id}','DiaryController@update');
    Route::post('community-post/{rid}','CommunityServiceController@update')->name('comm-update');
    Route::post('chapel/remark/update','CommunityServiceController@chapel_update_remark')->name('chapel-remark-update');
    Route::post('spirit-post/{rid}','CommunityServiceController@spirit_update')->name('spirit-update');
    Route::post('physical-post/{rid}','CommunityServiceController@physical_update')->name('physical-update');
    Route::post('community-post','CommunityServiceController@store')->name('comm-store');
    Route::post('community-verify','CommunityServiceController@update_verify')->name('ess_verify');



    Route::post('remark-post','CommunityServiceController@remark_store')->name('comm-remark');
    Route::post('chapel/remark/post','CommunityServiceController@chapel_remark')->name('spirit-remark');
    Route::post('remark-update','CommunityServiceController@remark_update')->name('comm-update');
    Route::post('edu-post','EducationController@create')->name('educ-create');
    Route::post('edu-update/{id}','EducationController@update')->name('educ-update');
    Route::post('prof-skills/alpha_add','AttachmentController@alpha_add')->name('alpha-add');
    Route::post('prof-skills/{id}','AttachmentController@update_prof_skill');
    Route::post('updateCourses/{id}','EducationController@updateOtherCourses')->name('updateCourse');
    Route::post('PostCourses','EducationController@postOtherCourses')->name('PostCourses');
    Route::post('ment/update','MentorController@update')->name('ment_update');
    Route::post('img_upload','PagesController@getFile')->name('upload');
    //Autobiography Routes
    Route::get('autobio','AutoBioController@index')->name('biography');
    Route::post('auto/post','AutoBioController@store')->name('auto-post');

    Route::post('auto/update','AutoBioController@update')->name('auto-update');

    Route::get('community','CommunityServiceController@index')->name('community-index');
    Route::get('community-show/{formID}','CommunityServiceController@show')->name('comm-show');
    Route::get('prof-skills','AttachmentController@skill')->name('prof-skills');
    Route::get('prof-skills/{id}','AttachmentController@show_prof_skill');
    Route::get('prof-skills/{id}/edit','AttachmentController@edit_prof_skill');
    Route::get('community-token/{token}','CommunityServiceController@token')->name('comm-token');
    //spiritual fitness route for getting information for sending email
    Route::get('spirit-token/{token}','CommunityServiceController@spirit_token')->name('spiritual-token');

    //Physical fitness route for getting information for sending email
    Route::get('physical-token/{token}','CommunityServiceController@physical_token')->name('physical-token');

    Route::any('community-edit/{rid}','CommunityServiceController@edit')->name('comm-edit');
    Route::any('chapel-edit/{rid}','CommunityServiceController@chapel_edit')->name('chapel-edit');
    Route::get('physical-edit/{rid}','CommunityServiceController@physical_edit')->name('physical-edit');
    Route::get('physical_exercise','CommunityServiceController@physical')->name('physical-index');

    Route::get('sp_fitness','CommunityServiceController@spiritual')->name('spirit-index');

    Route::get('education','EducationController@index')->name('educ-index');

    Route::get('edu-show/{id}','EducationController@show')->name('educ-show');

    Route::get('edu-edit/{id}','EducationController@edit')->name('educ-edit');

    Route::get('otherCourses','EducationController@SeeOtherCourses')->name('education.otherCourses');

    Route::get('seeCourses/{id}','EducationController@showOtherCourses')->name('viewCourses');

    Route::get('editCourses/{id}','EducationController@EditOtherCourses')->name('editCourses');

    Route::get('showment/{book}', 'PagesController@displayMentor')->name('displayMentor');

    Route::get('file/doc','PagesController@show_file')->name('data-file');

    Route::get('department/{id}', 'SchoolController@getSchoolDepartments')->name('school.department');
    Route::get('program/{department}', 'SchoolController@get_program')->name('department.program');

    Route::get('community/return/warden','CommunityServiceController@warden')->name('return_warden_email');
    Route::get('community/return/chapel','CommunityServiceController@chaplain')->name('return_chap_email');
    });
});

Route::middleware(['guest'])->group(function(){
    Route::get('/anylogin',function(){return view('admin.single');})->name('singleapp');
});

Route::get('/reject','DataController@reject')->name('reject'); //rejected PER datatable
Route::get('/approved','DataController@approve')->name('approve'); // approved PER datatable
Route::get ('admin/users', 'DataController@json')->name('json'); //student dataTables
Route::get ('admin/pending', 'DataController@pending')->name('pending'); //PER pending dataTables
Route::get ('admin/staff', 'DataController@staff')->name('staff'); //staff datatable
Route::get ('admin/staff/disabled', 'DataController@staff_disabled')->name('disabled_staff'); //disabled_staff datatable
Route::get('admin/student/graduated','DataController@graduated')->name('graduated');

Route::get('other/reject','DataController@Jnr_reject')->name('Jnrreject'); //rejected PER datatable
Route::get('other/approved','DataController@Jnr_approve')->name('Jnrapprove'); // approved PER datatable
Route::get ('other/admin/users', 'DataController@Jnr_json')->name('Jnrjson'); //student dataTables
Route::get ('/other/admin/pending', 'DataController@Jnr_pending')->name('Jnrpending'); //PER Jnrpending dataTables


//Route for the Educational Support Services
Route::prefix('admin')->group(function(){
    Route::get('/',                       'AdminController@index')->name('admin.dashboard');
    Route::get('/get/user/{target}',      'AdminController@getStudentData')->name('tblUserData');//fetching users into the modal for edit
    Route::get('/login',                  'Auth\adminLoginController@showLoginForm')->name('admin.login');
    Route::get('/uzers',                  'AdminController@usershow')->name('usershow'); //Displaying users for the admin
    Route::get('/show/ajax/users',        'AdminController@get_datatable')->name('ajax_users');
    Route::get('/show/{reg_num}',         'AdminController@show')->name('showuser');
    Route::get('/d_list',                 'AdminController@dynamic')->name('d_list');

resources/views/blueprint.blade.php
<!Doctype html>
<html lang="{{ config('app.locale')}}">
    <head>
        <meta http-equiv="pragma" content="no-cache" />
        <meta http-equiv="expires" content="-1" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>Green Book | User</title>
        <link rel="stylesheet" href="{{asset('css/paper.min.css')}}" />
        <link rel="stylesheet" href="{{asset('css/style.css')}}" />
        <link rel="stylesheet" href="{{asset('css/picker.min.css')}}" />
        <link rel="stylesheet" href="{{asset('assets/css/icons.css')}}" />
        <link rel="shortcut icon" href="{{{ asset('logoo.png') }}}">
        <link rel="stylesheet" href="{{asset('css/bootstrap-select.min.css')}}" />
        <link rel="stylesheet" href="{{asset('css/alertify.min.css')}}">
        <link rel="stylesheet" href="{{asset('css/alertify-bootstrap.min.css')}}" />
        <link href="https://fonts.googleapis.com/css?family=Alegreya|Allura|Calligraffitti|Cinzel|Cinzel+Decorative|Cormorant+Garamond|Cormorant+Upright|Courgette|Fontdiner+Swanky|Great+Vibes|Italianno|Josefin+Slab|Kurale|Lora|Merienda|Mogra|Mr+De+Haviland|Noto+Serif|Playball|Raleway|Sacramento|Slabo+13px|Slabo+27px|Spectral|Tangerine|Yellowtail" rel="stylesheet">
        <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet" />
        <!-- <script src="{{ asset('js/jquery-3.2.1.js') }}"></script> -->
        <!-- <script src="{{ asset('js/bootstrap.min.js') }}"></script> -->
        <script src="{{ asset('js/app.js') }}"></script>
        <script src="{{ asset('js/picker.min.js')}}"></script>
        <script src="{{asset('js/bootstrap-select.min.js')}}"></script>
        <script src="{{asset('js/alertify.min.js')}}"></script>
        <script src="{{asset('js/ckeditor1/ckeditor.js')}}"></script>
        <script>
          $(document).ready(function(){

            $(function () {
              $('[data-toggle="popover"]').popover()
            });

          })
          </script>
    </head>

@include('layout.user-header')
<body>
    <main id="ess">
        <div class="container" style="width: 90%">
            <div class="row">
                <div class="col-md-9">
                    <h2 style="color:white" class="cinzel text-uppercase"><i class="fa fa-university" aria-hidden="true"></i> The Green book
                        <small style="color:#e0e0e0;" class="text-uppercase text-font"> Practical Experience Record</small></h2>
                </div>

                <div class="col-md-3" style="background-color: ; margin-top: 10px">
                    <h3 style="color:white" class="cinzel text-uppercase">
                        <small style="color:#e0e0e0;" class="text-capitalize text-font"><em>Level : {{\Illuminate\Support\Facades\Auth::user()->level}}</em></small>
                    </h3>
                </div>
            </div>
        </div>
    </main>

    <section id="breadcrumb">
        <div class="container" style="width: 90%">
            <ol class="breadcrumb" id="bread">
                <li class="active">Dashboard</li>
                <li class="cinzel"><b>REGENT UNIVERSITY COLLEGE OF SCIENCE AND TECHNOLOGY</b></li>
            </ol>
        </div>
    </section>



    <div class="container" style="width: 90%">
        @if (count($errors) > 0)
            <div class="alert alert-warning">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif


            @if (\Session::has('success'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('success') !!}</li>
                    </ul>
                </div>
            @endif


      @if($defer->defer_status == '0')
        <div class="row">
            <div class="col-md-3" id="sidenav">
                <div class="list-group text-font">
                    <a href="#" class="list-group-item panel-color"><i class="fa fa-cogs fa-fw fa-2x" aria-hidden="true"></i> Menu</a>
                    @if(!$personal_details)
                    <div id="ajax">
                        <a  href="{{route('personal.create')}}" class="list-group-item">PERSONAL DETAILS<i class="fa fa-address-book pull-right text-success" aria-hidden="true"></i></a>
                    </div>
                    @else
                        <div id="ajax">
                            <a  href="{{route('personal.show')}}" role="button" class="list-group-item">PERSONAL DETAILS<i class="fa fa-check pull-right" aria-hidden="true" style="padding-left:30% !important;"></i></a>
                        </div>
                    @endif
                    <div id="ajax">
                        <a  class="list-group-item" role="button" href="{{route('mentor.create')}}">MENTOR<span class="badge" style="background-color:#263;">{{$ctm}}</span></a>
                    </div>
                    <a class="list-group-item" role="button" data-toggle="collapse" href="#diaryCollapse" aria-expanded="false" aria-controls="diaryCollapse">DIARY <i class="fa fa-user"></i> <span class="badge" style="background-color:#263;">{{$diary->count()}}</span></a>
                    <div class="collapse" id="diaryCollapse">
                        <div id="ajax">
                            @foreach ($diary as $diaries)
                                <a class="list-group-item text-style" style="color:#CC0000;"  href="{{route('diary.edit',[$diaries->id])}}"><i class="fa fa-book"></i> <em>{{$diaries->title}}</em><i class="badge">{{$diaries->date}}</i></a>
                            @endforeach
                        </div>
                    </div>
                    <a class="list-group-item" role="button" data-toggle="collapse" href="#attachCollapse" aria-expanded="false" aria-controls="attachCollapse">INDUSTRIAL ATTACHMENT <span class="badge" style="background-color:#263;">{{$attachment->count()}}</span></a>
                    <div class="collapse" id="attachCollapse">
                        <div id="ajax">
                            @if($attachment->isEmpty())
                                <a class="list-group-item"> You havent Provided Any data Yet</a>
                            @else
                                @foreach ($attachment as $attach)
                                    <a class="list-group-item text-style" href="{{ route('attach.show',[$attach->id])}}" >{!! html_entity_decode('<b>'.$attach->start_date .'</b> to <b>' .$attach->end_date.'</b>') !!}</a>
                                @endforeach
                            @endif
                        </div>
                    </div>
                    <a class="list-group-item" href="#profCollapse"  role="button" data-toggle="collapse" aria-expanded="false" aria-controls="profCollapse">PROFESSIONAL SKILL <span class="badge" style="background-color:#263;">{{$pskill_count}}</span></a>
                    <div class="collapse" id="profCollapse">
                        @if($pskills->isEmpty())
                            <a class="list-group-item" href="#">You havent Provided Any data Yet</a>
                        @else
                            <div id="ajax">
                                @foreach($pskills as $skills)
                                    <a class="list-group-item text-style" style="color:#CC0000;" href="{{'/prof-skills/'.$skills->id}}" ><i class="fa fa-eye" ></i> <em>{{$skills->title}}</em></a>
                                @endforeach
                            </div>
                        @endif
                    </div>
                    <a class="list-group-item" href="#eduCollapse" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="profCollapse">EDUCATION AND EXAMINATION <span class="badge" style="background-color:#263;">{{$times}}</span></a>
                    <div class="collapse" id="eduCollapse">
                        @if($education->isEmpty())
                            <a class="list-group-item" href="#">You havent Provided Any data Yet</a>
                        @else
                            <div id="ajax">
                                @foreach($education as $educ)
                                    <a class="list-group-item text-style" style="color:#CC0000;" href="{{'/edu-show/'.$educ->id}}" ><i class="fa fa-eye" ></i> <em>{{$educ->sch_name}}</em></a>
                                @endforeach
                            </div>
                        @endif
                    </div>
                    <a class="list-group-item" href="#courseCollapse" role="button" data-toggle="collapse" aria-expanded="false">OTHER COURSES <span class="badge" style="background-color:#263;">{{$count_courses}}</span></a>
                    <div class="collapse" id="courseCollapse">
                        @if($course->isEmpty())
                            <a class="list-group-item" href="#">You havent Provided Any data Yet</a>
                        @else
                            <div id="ajax">
                                @foreach($course as $courses)
                                    <a class="list-group-item text-style" style="color:#CC0000;" href="{{'/seeCourses/'.$courses->id}}" ><i class="fa fa-eye" ></i> <em>{{$courses->cours_name}}</em></a>
                                @endforeach
                            </div>
                        @endif
                    </div>

                    <a class="list-group-item" href="#health" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="profCollapse">HEALTH AND FITNESS <span class="badge" style="background-color:#263;">3</span></a>
                    <div class="collapse" id="health">
                        <div id="ajax">
                            <a class="list-group-item text-style" style="color:#CC0000;" href="{{route('community-index')}}" ><em>Community Service </em>  <span class="badge text-font" style="background-color:#263;">{{$community_count}}</span></a>
                            <a class="list-group-item text-style" style="color:#CC0000;" href="{{route('spirit-index')}}" ><em>Spiritual Fitness</em>   <span class="badge text-font" style="background-color:#263;">{{$chapel_count}}</span></a>
                            <a class="list-group-item text-style" style="color:#CC0000;" href="{{route('physical-index')}}" ><em>Physical Fitness </em>   <span class="badge text-font" style="background-color:#263;">{{$physical_count}}</span></a>
                        </div>

                    </div>
                    <!-- <a class="list-group-item" href="#profCollapse" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="profCollapse">PHYSICAL EXERCISES <span class="badge">0</span></a>
                    <a class="list-group-item" href="#profCollapse" role="button" data-toggle="collapse" aria-expanded="false" aria-controls="profCollapse">SPIRITUAL EXERCISES <span class="badge">0</span></a> -->

                </div>
            </div>

                @yield('content')



            </div>
        </div>
      @else
      <div>
        <h1 class="cinzel text-center  text-muted"><b>You can't perform any activity unless you are reinstated !!</b></h1>
        <h3 class="text-center text-muted">
          <i class="fa fa-exclamation-triangle fa-3x" aria-hidden="true"></i>
        </h3>
      </div>
      <br /><br /><br />
      @endif



    <div class="modal fade" id="photo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title cinzel" id="myModalLabel">CHANGE PROFILE PHOTO</h4>
                </div>
                <div class="modal-body">
                  <form class="form-inline" id="body-pic" action="{{route('upload')}}" enctype="multipart/form-data" method="post">
                      {{csrf_field()}}
                      <div class="form-group">
                        <label for="exampleInputName2">Name</label>
                        <input type="hidden" value="{{@$pass->password}}" id="pass"/>
                        <input type="file" class="form-control" name="picture" id="file_upload" required>
                      </div>
                      <button type="submit" class="btn btn-primary">Upload</button>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
  </div>



  @include('book.page-footer')
@stack('scripts')
</body>
</html>

resources/views/default.blade.php
<!doctype html>
<html lang="{{ config('app.locale') }}" >
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Welcome To The PER</title>

        <!-- Fonts -->
          <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
          <!-- <link href="{{asset('css/paper.css')}}" rel="stylesheet" type="text/css"/> -->
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
          <link rel="stylesheet" href="{{asset('materialize/css/materialize.min.css')}}" />
          <link href="{{asset('css/style.css')}}" rel="stylesheet" type="text/css"/>
          <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet"/>
          <link href="https://fonts.googleapis.com/css?family=Alegreya|Allura|Calligraffitti|Cinzel|Cinzel+Decorative|Cormorant+Garamond|Cormorant+Upright|Courgette|Fontdiner+Swanky|Great+Vibes|Italianno|Josefin+Slab|Kurale|Lora|Merienda|Mogra|Mr+De+Haviland|Noto+Serif|Playball|Raleway|Sacramento|Slabo+13px|Slabo+27px|Spectral|Tangerine|Yellowtail" rel="stylesheet">
          <link href="{{asset('css/welcome.css')}}" rel="stylesheet" type="text/css" />
          <script src="{{ asset('js/jquery-3.2.1.js') }}"></script>
          <script src="{{asset('materialize/js/materialize.min.js')}}"></script>
    </head>
    <body class="white bd-color">
        <div class="wrapper">

          <div class="navbar-fixed" >
              <nav class="transparent">
                <div class="nav-wrapper">
                  <a href="#!" class="brand-logo cinzel"><img src="{{asset('logoo.png')}}" style="height:65px"/></a>
                  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                  <ul class="right hide-on-med-and-down cinzel">
                    <li class="active"><a href="{{route('book.index')}}">Student</a></li>
                    <li><a href="/admin">E.S.S</a></li>
                  </ul>
                  <ul class="side-nav cinzel" id="mobile-demo">
                    <li class="active"><a href="/book">Student</a></li>
                    <li><a href="/admin">E.S.S</a></li>
                  </ul>
                </div>
              </nav>
        </div>

          <div class="container" style="margin-top:10%;">
              <div class="row">
                <div class="col s12">
                  <h3 class="cinzel center-align">The Practical Experience Record,</h3>
                </div>
                    <div class="col s6 offset-s3">
                      <h3 class="cinzel center-align">Green Book</h3>
                    </div>

                  <div class="col s6 offset-s3">
                    <nav class="transparent">
                      <div class="nav-wrapper">
                        <form>
                          <div class="input-field">
                            <input id="search_field" type="search" required>
                            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                            <i class="material-icons">close</i>
                          </div>
                        </form>
                        <div class="progress" id="animate">
                            <div class="indeterminate"></div>
                        </div>
                      </div>
                    </nav>
                  </div>


                  <div class="col s6 offset-s3" id="search-results" style="margin-top:5%">

                  </div>

                </div>
            </div>


      <script>
          $(document).ready(function(){
              $('#animate').hide();
              $(".button-collapse").sideNav();
              $('#search_field').on('keyup',function(e){
                  e.preventDefault();
                    const value = $('#search_field').val();
                      if(value !==''){
                        $('#search-results').show();
                        $.ajax({
                          headers: {
                            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                          },
                          type:'get',
                          url:'search/'+ value,
                          beforeSend:function(){
                            $('#animate').show();
                          },
                          success:function(data){
                            $('#search-results').html(data);
                              $('#animate').hide();
                          },
                          error:function(){
                            console.log('it failed')
                          }
                        })
                      }
                      else if (value ==='') {
                        $('#search-results').hide();
                      }
              })
          });
        </script>
      </div>
    </body>
</html>

resources/views/email.blade.php
@component('mail::message')
# Mentor Endorsement

The Following student is requesting for endorsement as a mentor
<strong>
{{$std_name}}
<br />
{{$id}}
</strong>

@component('mail::button',['url'=>$url])
Click  here
@endcomponent

Thanks,<br>
{{ config('app.name') }}
@endcomponent

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/live-search.blade.php
@foreach($searchUser as $u)
    <a href="#" class=""><b>{{$u->name}}</b>
    </a>
@endforeach

resources/views/return.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
@include('layout.user-header')
@yield('dash-header')
<body>
  <div class="container">
    <h4 class="text-font">You have successfully approved the Following Student as his level {{$user->level}} mentor.</h4>
<hr />      <div class="row">
            <div class="col-md-4">
              <ul class="list-group">
                <li class="list-group-item">{{$user->name}}</li>
                <li class="list-group-item">{{$user->reg_num}}</li>
                <li class="list-group-item">{{$user->email}}</li>
                <li class="list-group-item">{{$user->school}}</li>
                <li class="list-group-item">{{$user->phone1}}</li>
              </ul>
            </div>
              <div class="col-md-4">
                <img class="img-thumbnail"  src="" alt="Student Image Here"/>

              </div>
          </div>

  </div>
</body>


</html>

resources/views/search-results.blade.php
          <ul class="collection with-header">
            @if($get_field->isEmpty())
            <li class="collection-headers">
              <h5 class="cinzel">No Results</h5>
            </li>

            @else
            <li class="collection-headers">
              <h5 class="cinzel">   {{count($get_field)}} Results</h5>
            </li>

              @foreach($get_field as $fetch)
              <li class="collection-item transparent cinzel">
                <div>
                  <strong>

                <a href="{{route('getAll',["reg_num"=>$fetch->reg_num])}}" style="color:white">{{$fetch->surname}} {{$fetch->othernames}}</a>
                  </strong>
                <a href="{{route('getAll',["reg_num"=>$fetch->reg_num])}}" class="secondary-content cinzel">
                  <i class="material-icons">send</i></a>
              </div>
              </li>
              @endforeach
              @endif
          </ul>