routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('custom','AdminController@props')->name('props');
Route::get('/','PagesController@welcome')->name('welcome-home');

Route::namespace('Auth')->group(function (){
    Route::get('login','LoginController@showLoginForm')->name('login');
    Route::post('login','LoginController@postLogin')->name('post.login');
    Route::post('user/logout','LoginController@logout')->name('user.logout');

});

// Route::group(['middleware'=>'guest'], function(){
Route::get('com_service/verify/{token}', 'mailController@community_val_request')->name('community_validation');

//For accessing chapel service record for the student
Route::get('chapel_service/verify/{token}', 'mailController@chapel_val_request')->name('chapel_validation');
//For accessing physical fitness record for the student
Route::get('physical/xdfbbsbfjsdbfjf/{token}','mailController@physical_val_request')->name('physical_validation');

Route::get('warden/verify/{token}', 'mailController@warden_val_request')->name('warden_validation');
Route::get('remark/chaplain/{token}', 'mailController@remark_chap_val_request')->name('chaplain_remark_validation');
Route::post('community-warden-verify','CommunityServiceController@warden_update_verify')->name('community_warden_verify');
Route::post('chaplain-alpha-remark','CommunityServiceController@remark_chaplain')->name('remark_of_chaplain');
// });


Route::post('chapel-verify','CommunityServiceController@chapel_update_verify')->name('ess_chapel_verify');

//Physical fitness verification by the ESS if he wants to endorse the peculiar request
Route::post('physical-verify','CommunityServiceController@physical_update_verify')->name('ess_physical_verify');


Route::middleware(['auth:web'])->group(function(){

    Route::prefix('student')->group(function (){

    Route::get('pass_word',function(){
        return view('auth.passwords.change-pass');
    })->name('key');

    Route::post('pass','PagesController@password');
    Route::get('help','PagesController@help')->name('help');

    Route::resource('book','PagesController');

    Route::prefix('personal-details')->group(function (){

        Route::get('index', 'PagesController@show')->name('personal.show');
        Route::any('create','PagesController@create')->name('personal.create');
        Route::any('edit',  'PagesController@edit')->name('personal.edit');

    });

    Route::resource('diary','DiaryController');
    Route::resource('attach','AttachmentController');
    Route::resource('mentor','MentorController');
    Route::get('mentor/email/{token}','MentorController@getemail');
    Route::any('send-request-intern','AttachmentController@intern_notify')->name('intern-notification');
    Route::post('chapel_save','CommunityServiceController@ChapelSave')->name('chapel-post');
    Route::post('physical_save','CommunityServiceController@post_phyiscal_data')->name('physical-post');
    Route::post('attach/{id}','AttachmentController@update');
    Route::post('/book/get/{reg_num}','PagesController@update');
    Route::post('/diary/{id}','DiaryController@update');
    Route::post('community-post/{rid}','CommunityServiceController@update')->name('comm-update');
    Route::post('chapel/remark/update','CommunityServiceController@chapel_update_remark')->name('chapel-remark-update');
    Route::post('spirit-post/{rid}','CommunityServiceController@spirit_update')->name('spirit-update');
    Route::post('physical-post/{rid}','CommunityServiceController@physical_update')->name('physical-update');
    Route::post('community-post','CommunityServiceController@store')->name('comm-store');
    Route::post('community-verify','CommunityServiceController@update_verify')->name('ess_verify');



    Route::post('remark-post','CommunityServiceController@remark_store')->name('comm-remark');
    Route::post('chapel/remark/post','CommunityServiceController@chapel_remark')->name('spirit-remark');
    Route::post('remark-update','CommunityServiceController@remark_update')->name('comm-update');
    Route::post('edu-post','EducationController@create')->name('educ-create');
    Route::post('edu-update/{id}','EducationController@update')->name('educ-update');
    Route::post('prof-skills/alpha_add','AttachmentController@alpha_add')->name('alpha-add');
    Route::post('prof-skills/{id}','AttachmentController@update_prof_skill');
    Route::post('updateCourses/{id}','EducationController@updateOtherCourses')->name('updateCourse');
    Route::post('PostCourses','EducationController@postOtherCourses')->name('PostCourses');
    Route::post('ment/update','MentorController@update')->name('ment_update');
    Route::post('img_upload','PagesController@getFile')->name('upload');
    //Autobiography Routes
    Route::get('autobio','AutoBioController@index')->name('biography');
    Route::post('auto/post','AutoBioController@store')->name('auto-post');

    Route::post('auto/update','AutoBioController@update')->name('auto-update');

    Route::get('community','CommunityServiceController@index')->name('community-index');
    Route::get('community-show/{formID}','CommunityServiceController@show')->name('comm-show');
    Route::get('prof-skills','AttachmentController@skill')->name('prof-skills');
    Route::get('prof-skills/{id}','AttachmentController@show_prof_skill');
    Route::get('prof-skills/{id}/edit','AttachmentController@edit_prof_skill');
    Route::get('community-token/{token}','CommunityServiceController@token')->name('comm-token');
    //spiritual fitness route for getting information for sending email
    Route::get('spirit-token/{token}','CommunityServiceController@spirit_token')->name('spiritual-token');

    //Physical fitness route for getting information for sending email
    Route::get('physical-token/{token}','CommunityServiceController@physical_token')->name('physical-token');

    Route::any('community-edit/{rid}','CommunityServiceController@edit')->name('comm-edit');
    Route::any('chapel-edit/{rid}','CommunityServiceController@chapel_edit')->name('chapel-edit');
    Route::get('physical-edit/{rid}','CommunityServiceController@physical_edit')->name('physical-edit');
    Route::get('physical_exercise','CommunityServiceController@physical')->name('physical-index');

    Route::get('sp_fitness','CommunityServiceController@spiritual')->name('spirit-index');

    Route::get('education','EducationController@index')->name('educ-index');

    Route::get('edu-show/{id}','EducationController@show')->name('educ-show');

    Route::get('edu-edit/{id}','EducationController@edit')->name('educ-edit');

    Route::get('otherCourses','EducationController@SeeOtherCourses')->name('education.otherCourses');

    Route::get('seeCourses/{id}','EducationController@showOtherCourses')->name('viewCourses');

    Route::get('editCourses/{id}','EducationController@EditOtherCourses')->name('editCourses');

    Route::get('showment/{book}', 'PagesController@displayMentor')->name('displayMentor');

    Route::get('file/doc','PagesController@show_file')->name('data-file');

    Route::get('department/{id}', 'SchoolController@getSchoolDepartments')->name('school.department');
    Route::get('program/{department}', 'SchoolController@get_program')->name('department.program');

    Route::get('community/return/warden','CommunityServiceController@warden')->name('return_warden_email');
    Route::get('community/return/chapel','CommunityServiceController@chaplain')->name('return_chap_email');
    });
});

Route::middleware(['guest'])->group(function(){
    Route::get('/anylogin',function(){return view('admin.single');})->name('singleapp');
});

Route::get('/reject','DataController@reject')->name('reject'); //rejected PER datatable
Route::get('/approved','DataController@approve')->name('approve'); // approved PER datatable
Route::get ('admin/users', 'DataController@json')->name('json'); //student dataTables
Route::get ('admin/pending', 'DataController@pending')->name('pending'); //PER pending dataTables
Route::get ('admin/staff', 'DataController@staff')->name('staff'); //staff datatable
Route::get ('admin/staff/disabled', 'DataController@staff_disabled')->name('disabled_staff'); //disabled_staff datatable
Route::get('admin/student/graduated','DataController@graduated')->name('graduated');

Route::get('other/reject','DataController@Jnr_reject')->name('Jnrreject'); //rejected PER datatable
Route::get('other/approved','DataController@Jnr_approve')->name('Jnrapprove'); // approved PER datatable
Route::get ('other/admin/users', 'DataController@Jnr_json')->name('Jnrjson'); //student dataTables
Route::get ('/other/admin/pending', 'DataController@Jnr_pending')->name('Jnrpending'); //PER Jnrpending dataTables


//Route for the Educational Support Services
Route::prefix('admin')->group(function(){
    Route::get('/',                       'AdminController@index')->name('admin.dashboard');
    Route::get('/get/user/{target}',      'AdminController@getStudentData')->name('tblUserData');//fetching users into the modal for edit
    Route::get('/login',                  'Auth\adminLoginController@showLoginForm')->name('admin.login');
    Route::get('/uzers',                  'AdminController@usershow')->name('usershow'); //Displaying users for the admin
    Route::get('/show/ajax/users',        'AdminController@get_datatable')->name('ajax_users');
    Route::get('/show/{reg_num}',         'AdminController@show')->name('showuser');
    Route::get('/d_list',                 'AdminController@dynamic')->name('d_list');

app/Diary.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Diary extends Model
{
    use SoftDeletes;

    protected  $fillable = ['user_id','title','body','date'];



    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/DiaryController.php
<?php /** @noinspection PhpUndefinedMethodInspection */

namespace App\Http\Controllers;
use App\Diary;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class DiaryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */


    public function index()
    {
        return view('diary.diaryindex');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {


        return view('diary.story');

    }


    public function store(Request $request)
    {
        $data = $request->validate([
            'date' =>'required',
            'title' =>'required',
            'body' =>'required',
        ]);



        $user = Auth::user();

        DB::beginTransaction();

        $user->diary()->create($data);

        DB::commit();


        return redirect()->back()->with('success',"Diary : {$request->input('title')} successfully created");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {

        return view('diary.show', compact('personal_details','mentor','diary','dinfo','count','num_attach','attachment','img','pskills','pskill_count'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
          $user = Auth::user();
          $user_diary = $user->diary()->find($id);

      return view('diary.edit',compact('user_diary'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return void
     */
    public function update(Request $request, $id)
    {


       $diary = Diary::find($id);

        $data = $request->validate([
            'date' =>'required',
            'title' =>'required',
            'body' =>'required',
        ]);

        DB::beginTransaction();

        $diary->update($data);

        DB::commit();

        return redirect()->back()->with('success',"Diary : {$request->input('title')} successfully updated");


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/diary/diaryindex.blade.php
<!Doctype html>
    <html>
      <head>
          <title></title>
          <link rel="stylesheet" href="{{asset('css/bootstrap4.min.css')}}">
          <link rel="stylesheet" href="{{asset('css/mdb.min.css')}}">
          <link rel="stylesheet" href="{{asset('CSS/font-awesome.min.css')}}">
          <link rel="stylesheet" href="{{asset('css/style.css')}}">
          <link href="https://fonts.googleapis.com/css?family=Alegreya|Cinzel+Decorative|Cormorant|Courgette|Fontdiner+Swanky|Great+Vibes|Lobster|Lora|Mogra|Mr+Dafoe|Mr+De+Haviland|Noto+Serif|Oregano|Poiret+One|Pompiere|Raleway|Slabo+27px|Spectral|Vibur|Yellowtail" rel="stylesheet">
          <script src="{{asset('js/jquery-3.2.1.js')}}"></script>
           <script src="{{asset('js/tether.js')}}"></script>
           <script src="{{asset('js/bootstrap4.min.js')}}"></script>
           <script src="{{asset('js/mdb.js')}}"></script>
     <style>
      @import url('https://fonts.googleapis.com/css?family=Alegreya|Caveat|Cinzel|Cinzel+Decorative|Cormorant+Infant|Courgette|Dancing+Script|Fontdiner+Swanky|Great+Vibes|IM+Fell+Great+Primer+SC|Josefin+Slab|Kalam|Kurale|Lobster|Lora|Marck+Script|Mogra|Mr+Dafoe|Mr+De+Haviland|Noto+Serif|Oregano|Playball|Poiret+One|Pompiere|Sacramento|Satisfy|Slabo+27px|Spectral|Vibur|Yellowtail|Zilla+Slab');
      </style>
    </head>

          <body>
              <div class="jumbotron" id="diary">

                        <h1 class="text-center animated fadeIn" style="padding-top:8%; font-family: 'Yellowtail', cursive;">Welcome To Your Diary  <i class="fa fa-book" aria-hidden="true"></i></h1>
                        </>
                        <br />

                        <div class="div-center">

                        <p class="text-justify text-font t1">This portion records all the GSGR
                        activities as well as any memorable events in the University. It records details of relevant training and workshops organised
                        inside and outside The University.Example: Student Internships, Seminars, Programmes and Workshops Relevant to the program of
                        study.</p>

                      </div>

                            <div class="text-center" style="padding-bottom:8%; padding-top: 5%">
                                  <a class="btn btn-amber" href="/diary/create"><i class="fa fa-dashboard" aria-hidden="true"></i> Proceed....</a>
                            </div>
                      <div class="text-center">
                        <a href="#order" class="non-style"><i class="fa fa-angle-double-down fa-5x animated bounce infinite" aria-hidden="true"></i></a>
                      </div>


              </div>
              <div class="container-fluid " id="order" >
                  <div class="row">
                    <div class="col-md-3 wow fadeInUp" data-wow-delay="0.10s">
                      <div class="">
                        <div class="card-block blocker">
                          <h2><a href="/attach/create" class="non-fa"><i class="fa fa-newspaper-o fa-5x" aria-hidden="true"></i></h2></a>
                          <h4>Internship</h4>
                        </div>
                      </div>
                   </div>

                   <div class="col-md-3 wow fadeInUp" data-wow-delay="0.20s">
                     <div class="">
                       <div class="card-block blocker">
                         <h2><i class="fa fa-newspaper-o fa-5x fa-spin" aria-hidden="true"></i></h2>
                         <h4>Internship</h4>
                       </div>
                     </div>
                  </div>

                  <div class="col-md-3 wow fadeInUp" data-wow-delay="0.30s">
                    <div class="">
                      <div class="card-block blocker">
                        <h2><i class="fa fa-clone fa-5x" aria-hidden="true"></i></h2>
                        <h4>Internship</h4>
                      </div>
                    </div>
                 </div>
                  </div>


              </div>
          </body>

        <script>
        new WOW().init();
        </script>

    </html>

resources/views/diary/edit.blade.php
<script>
$('#graph').hide();
  $(document).ready(function(){
    CKEDITOR.replace( 'textbody').required;

  });
  </script>
@extends('blueprint')
@section('content')
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="text-font">Diary <small>(Details Of Training Received / Work Undertaken In Each Department)</small></h4>
            </div>
            <div class="panel-body text-font">
                <form method="post" action="{{route('diary.update',[$user_diary->id])}}">
                    @csrf

                    <div class="row">

                        <div class="form-group col-md-6">
                            <label class="col-md-4 ">DATE</label>
                            <div class="col-sm-8">
                                <input type="date" name="date" value="{{$user_diary->date}}"  class="form-control" id="date"  placeholder="date" autofocus/>
                            </div>
                        </div>


                        <div class="form-group col-md-6">
                            <label class="col-md-4" >TITLE</label>
                            <div class="col-md-8">
                                <input type="text" name="title" value="{{$user_diary->title}}" class="form-control" id="title" placeholder="Must Be Precise and Short"/>
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            <label class="col-md-6">BODY (<small> Details of training received / Work undertaken in each department </small>)</label>
                            <div class="col-md-12">
                                <textarea  class="form-control" rows="20" name="body" id="textbody">{{$user_diary->body}}</textarea>
                            </div>
                        </div>
                    </div>


                    <div class="text-center">
                        <button class="btn new-btn-green" id="btn-save">Save Record</button>
                    </div>
                </form>
            </div>
            <div class="panel-footer text-font">
                Regent University College Of Science and Technology
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function(){
            function side_nav(){
                $.ajax({
                    type:'get',
                    url:'/side_nav',
                    success:function(data){
                        $('#sidenav').html(data)
                    }
                })
            }
            CKEDITOR.replace( 'textbody').required;
        });
    </script>
@endpush

resources/views/diary/show.blade.php
<script>
$(document).ready(function(){
  CKEDITOR.replace( 'textbody');

  $('#ajax2 a').on('click',function(event){
    event.preventDefault();
    var $this = $(this);
    target = $this.data('target');
    $.ajax({
      method:'GET',
      url:target,
      beforeSend: function(){
          $("#replace").html('Working On...');
      },

      success:function(data){
        $("#replace").html(data);
        $("select").selectpicker('refresh');
        $('#bread').empty();
        if (target == '{{'/book/'}}'){
            $('#bread').append('<li><a href="/book">Dashboard</li></a><li><a href="#">Industrial Attachment</li><li><a href="#"><b>Professional Skill</b></li></a>');
        }
      }
    });
  });
});
</script>

      <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">
              <h4 class="text-font">Diary <small>(Details Of Training Received / Work Undertaken In Each Department)</small></h4>
          </div>
          <div class="panel-body">
            @if(count($dinfo)===1)
            <form method="" action="">
                  {{csrf_field()}}
                  <div class="form-group row" style="float:left;">
                    <label class="col-sm-2 ">DATE</label>
                        <div class="col-sm-8">
                            <input type="date" value="{{$dinfo->date}}"  class="form-control"  placeholder="date" autofocus readonly/>
                        </div>
                  </div>

                    <div class="form-group row" style="float:right;">
                      <label class="col-sm-4  col-md-offset-2">ID NUMBER</label>
                      <div class="col-sm-6">
                          <input type="number" name="reg_num" class="form-control" value="{{$dinfo->reg_num}}" readonly />
                      </div>
                  </div>
                        <br /><br />

                      <div class="panel-heading panel-danger">
                        <div class="row">
                          <label class="col-md-1" >TITLE</label>
                          <div class="col-sm-11">
                              <input type="text" value="{{$dinfo->title}}" class="form-control" placeholder="Enter title here" readonly/>
                          </div>

                        </div>
                    </div>

                    <div class="form-group">
                        <label>BODY (<small> Details of training received / Work undertaken in each department </small>)</label>
                        <textarea  class="form-control" value="" rows="5" name="body" id="textbody" readonly>{{$dinfo->body}}</textarea>
                  </div>
                  <div class="text-center" id="ajax2">
                    <a class="btn btn-primary" data-target="{{'/diary/'.$dinfo->id.'/edit'}}"><i class="fa fa-edit"></i> Make Changes</a>
                  </div>

            </form>

          </div>
          <div class="panel-footer text-font">
            Regent University College Of Science and Technology
          </div>
        </div>
      </div>

      @else
      <h4>No Data Available</h4>
      @endif

resources/views/diary/story.blade.php
@extends('blueprint')
@section('content')
<div class="col-md-9">
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="text-font">Diary <small>(Details Of Training Received / Work Undertaken In Each Department)</small></h4>
      </div>
            <div class="panel-body text-font">
              <form method="post" action="{{route('diary.store')}}">
                    @csrf

                  <div class="row">

                            <div class="form-group col-md-6">
                              <label class="col-md-4 ">DATE</label>
                                  <div class="col-sm-8">
                                      <input type="date" name="date"  class="form-control" id="date"  placeholder="date" autofocus/>
                                  </div>
                            </div>


                                <div class="form-group col-md-6">
                                    <label class="col-md-4" >TITLE</label>
                                        <div class="col-md-8">
                                            <input type="text" name="title" class="form-control" id="title" placeholder="Must Be Precise and Short"/>
                                        </div>
                                </div>

                                <div class="form-group col-md-12">
                                    <label class="col-md-6">BODY (<small> Details of training received / Work undertaken in each department </small>)</label>
                                    <div class="col-md-12">
                                         <textarea  class="form-control" rows="20" name="body" id="textbody"></textarea>
                                    </div>
                                </div>
                          </div>


                    <div class="text-center">
                      <button class="btn new-btn-green" id="btn-save">Save Record</button>
                    </div>
              </form>
            </div>
            <div class="panel-footer text-font">
              Regent University College Of Science and Technology
            </div>
      </div>
  </div>
@endsection

@push('scripts')
    <script>
        $(document).ready(function(){
            function side_nav(){
                $.ajax({
                    type:'get',
                    url:'/side_nav',
                    success:function(data){
                        $('#sidenav').html(data)
                    }
                })
            }
            CKEDITOR.replace( 'textbody').required;
        });
    </script>
    @endpush